name: Continuous Integration
on: [push]                    # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    - uses: actions/setup-dotnet@v1 # Adds a step to checkout the repository code
      with:
        dotnet-version: '3.1.x'
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - uses: act10ns/slack@v1
      with:
        status: starting
      if: always()

    - name: dotnet build
      run: dotnet build
    
    - name: dotnet test
      run: dotnet test

    - name: npm ci
      run: npm ci
      working-directory: ./DotnetTemplate.Web

    - name: npm build
      run: npm run build
      working-directory: ./DotnetTemplate.Web

    - name: npm lint
      run: npm run lint
      working-directory: ./DotnetTemplate.Web

    - name: npm test
      run: npm t
      working-directory: ./DotnetTemplate.Web

    - uses: act10ns/slack@v1
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(job.steps) }}
      if: always()